version: '3'

services:
  ikea-postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=user  
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    networks:
      - fullstack

  ikea_web:
    build: .
    ports: 
      - "8080:8080" 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - ikea-postgres
    networks:
      - fullstack

volumes:
    api:
    pgsqldata:
      
# Networks to be created to facilitate communication between containers
networks:
    fullstack:
      driver: bridge