version: '3'

services:
  pgsql:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=user  
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
      - POSTGRES_HOST=pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    networks:
      - fullstack

  app:
    build: .
    env_file:
      - .env
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - pgsql
    networks:
      - fullstack

volumes:
    api:
    pgsqldata:
      
# Networks to be created to facilitate communication between containers
networks:
    fullstack:
      driver: bridge