version: '3'

services:
  app:
    container_name: ikea_app
    build: .
    volumes:
        - api:/usr/src/app/
    ports: 
      - "8080:8080" 
    restart: on-failure
    depends_on:
      - pgsql

  pgsql:
    image: postgres:latest
    container_name: ikea_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  api:
  database_postgres:                  
